### ISSUE TITLE
Choosing a command with Tab causes suggestions to disappear

### ISSUE THREAD

**Issue by danielbrauer** [jechter/boltprompt#2] opened 2024-11-29 14:47 UTC
**Summary**
Bolt suggests commands, but requires extra input to complete a command and then show suggested arguments for the command. I think it should show arguments immediately.

**To reproduce**
1. type `bo`
2. Hit Tab to choose `boltprompt`
3. Hit space, or backspace followed by space

**Expected results**
After 2, I expect bolt to show a list of suggested parameters for `boltprompt`.

**Actual results**
After 2, suggestions disappear. They only reappear when I "nudge" it by entering a space.

**Comment by jechter** [comment] 2024-12-05 12:46
Hey @danielbrauer . This is by design - but certainly up for debate and I'm open to suggestions to making the design better. The problem is:
- Return will currently commit the selection *and* run the command.
- That means that if you just want to run e.g. `ls`, typing `l`+`s`+`return` will run just ls (which is expected). But if it displayed suggestions right away, it would autocomplete arguments which you might not want (forcing you to hit esc to close the suggestions before hitting return).

Maybe the solution would involve a state where suggestions are shown, but none is actively selected (requiring you to hit the down or up arrow keys to enter a "selection mode").

**Comment by danielbrauer** [comment] 2024-12-05 19:33
Showing suggestions without selecting one automatically could help here. I think in the case of Tab, though, I interpret it to mean “yes, and…” so I think I’d expect to have the first suggested argument selected after step 2. If I changed my mind, I’d hit Escape.

**Comment by jechter** [comment] 2024-12-09 09:58
> think in the case of Tab, though, I interpret it to mean “yes, and…” so I think I’d expect to have the first suggested argument selected after step 2. If I changed my mind, I’d hit Escape.

In my experience when I tried this, it very often would cause me to type commands I did not want. Because you don't know if further suggestions would pop up or not. For instance when you want to do `ls mydirectory/mysubdirectory`, it is inconvenient and unintuitive that you have to hit esc after tab-autocompleting `mysubdirectory` to avoid getting a suggestion further into the subdirectory (but only if mysubdirectory has any contents).

But I tried the idea of "showing suggestions without selecting one automatically" - until you start typing characters, when it will select a matching suggestion, and I think that works well. Pushed that change to the main branch, will be in the next release.

**Comment by jechter** [comment] 2024-12-09 09:59
Pushed a change which should improve this, let's see if this is intuitive in a while.

**Closed as completed by jechter** 2024-12-09 09:59 UTC
